/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'work' : null } |
  { 'academic' : null } |
  { 'personal' : null };
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Stats { 'totalTasks' : bigint, 'completedTasks' : bigint }
export interface Task {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [string],
  'category' : Category,
  'priority' : Priority,
}
export interface TaskInput {
  'title' : string,
  'dueDate' : [] | [string],
  'category' : Category,
  'priority' : Priority,
}
export interface _SERVICE {
  'createTask' : ActorMethod<[TaskInput], Task>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getDailyQuote' : ActorMethod<[], string>,
  'getTask' : ActorMethod<[bigint], Task>,
  'getTodayStats' : ActorMethod<[], Stats>,
  'toggleTaskCompletion' : ActorMethod<[bigint], Task>,
  'updateTask' : ActorMethod<[bigint, TaskInput], Task>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];