/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'work' : IDL.Null,
  'academic' : IDL.Null,
  'personal' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const TaskInput = IDL.Record({
  'title' : IDL.Text,
  'dueDate' : IDL.Opt(IDL.Text),
  'category' : Category,
  'priority' : Priority,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Text),
  'category' : Category,
  'priority' : Priority,
});
export const Stats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createTask' : IDL.Func([TaskInput], [Task], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getDailyQuote' : IDL.Func([], [IDL.Text], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTodayStats' : IDL.Func([], [Stats], ['query']),
  'toggleTaskCompletion' : IDL.Func([IDL.Nat], [Task], []),
  'updateTask' : IDL.Func([IDL.Nat, TaskInput], [Task], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'work' : IDL.Null,
    'academic' : IDL.Null,
    'personal' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TaskInput = IDL.Record({
    'title' : IDL.Text,
    'dueDate' : IDL.Opt(IDL.Text),
    'category' : Category,
    'priority' : Priority,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Text),
    'category' : Category,
    'priority' : Priority,
  });
  const Stats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
  });
  
  return IDL.Service({
    'createTask' : IDL.Func([TaskInput], [Task], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getDailyQuote' : IDL.Func([], [IDL.Text], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTodayStats' : IDL.Func([], [Stats], ['query']),
    'toggleTaskCompletion' : IDL.Func([IDL.Nat], [Task], []),
    'updateTask' : IDL.Func([IDL.Nat, TaskInput], [Task], []),
  });
};

export const init = ({ IDL }) => { return []; };